const { AttachmentBuilder } = require("discord.js");

const Image = {
  amnaStopwatch1: new AttachmentBuilder("./assets/images/amanStopwatch1.png"),
  amnaAlert1: new AttachmentBuilder("./assets/images/amnaAlert1.png"),
  amnaAlert2: new AttachmentBuilder("./assets/images/amnaAlert2.png"),
  amnaArrowDown1: new AttachmentBuilder("./assets/images/amnaArrowDown1.png"),
  amnaArrowUp1: new AttachmentBuilder("./assets/images/amnaArrowUp1.png"),
  amnaButtonOff1: new AttachmentBuilder("./assets/images/amnaButtonOff1.png"),
  amnaButtonOff2: new AttachmentBuilder("./assets/images/amnaButtonOff2.png"),
  amnaButtonOn1: new AttachmentBuilder("./assets/images/amnaButtonOn1.png"),
  amnaButtonOn2: new AttachmentBuilder("./assets/images/amnaButtonOn2.png"),
  amnaClear1: new AttachmentBuilder("./assets/images/amnaClear1.png"),
  amnaDelete1: new AttachmentBuilder("./assets/images/amnaDelete1.png"),
  amnaDev1: new AttachmentBuilder("./assets/images/amnaDev1.png"),
  amnaDice1: new AttachmentBuilder("./assets/images/amnaDice1.png"),
  amnaDice2: new AttachmentBuilder("./assets/images/amnaDice2.png"),
  amnaDice3: new AttachmentBuilder("./assets/images/amnaDice3.png"),
  amnaDice4: new AttachmentBuilder("./assets/images/amnaDice4.png"),
  amnaDice5: new AttachmentBuilder("./assets/images/amnaDice5.png"),
  amnaDice6: new AttachmentBuilder("./assets/images/amnaDice6.png"),
  amnaError1: new AttachmentBuilder("./assets/images/amnaError1.png"),
  amnaFooter1: new AttachmentBuilder("./assets/images/amnaFooter1.png"),
  amnaFooter2: new AttachmentBuilder("./assets/images/amnaFooter2.png"),
  amnaFooter3: new AttachmentBuilder("./assets/images/amnaFooter3.png"),
  amnaGameConntroler1: new AttachmentBuilder(
    "./assets/images/amnaGameConntroler1.png",
  ),
  amnaGithub1: new AttachmentBuilder("./assets/images/amnaGithub1.png"),
  amnaHome1: new AttachmentBuilder("./assets/images/amnaHome1.png"),
  AmnaIcon: new AttachmentBuilder("./assets/images/AmnaIcon.png"),
  amnaLeft1: new AttachmentBuilder("./assets/images/amnaLeft1.png"),
  amnaLoop1: new AttachmentBuilder("./assets/images/amnaLoop1.png"),
  amnaMessage1: new AttachmentBuilder("./assets/images/amnaMessage1.png"),
  amnaModeration1: new AttachmentBuilder("./assets/images/amnaModeration1.png"),
  amnaMusic1: new AttachmentBuilder("./assets/images/amnaMusic1.png"),
  amnaNu4: new AttachmentBuilder("./assets/images/amnaNu4.png"),
  amnaNum1: new AttachmentBuilder("./assets/images/amnaNum1.png"),
  amnaNum10: new AttachmentBuilder("./assets/images/amnaNum10.png"),
  amnaNum2: new AttachmentBuilder("./assets/images/amnaNum2.png"),
  amnaNum3: new AttachmentBuilder("./assets/images/amnaNum3.png"),
  amnaNum5: new AttachmentBuilder("./assets/images/amnaNum5.png"),
  amnaNum6: new AttachmentBuilder("./assets/images/amnaNum6.png"),
  amnaNum7: new AttachmentBuilder("./assets/images/amnaNum7.png"),
  amnaNum8: new AttachmentBuilder("./assets/images/amnaNum8.png"),
  amnaNum9: new AttachmentBuilder("./assets/images/amnaNum9.png"),
  amnaPlayPause1: new AttachmentBuilder("./assets/images/amnaPlayPause1.png"),
  amnaPrevious1: new AttachmentBuilder("./assets/images/amnaPrevious1.png"),
  amnaRight1: new AttachmentBuilder("./assets/images/amnaRight1.png"),
  amnaShuffle1: new AttachmentBuilder("./assets/images/amnaShuffle1.png"),
  amnaSkip1: new AttachmentBuilder("./assets/images/amnaSkip1.png"),
  amnaSlashCommand1: new AttachmentBuilder(
    "./assets/images/amnaSlashCommand1.png",
  ),
  amnaStaff1: new AttachmentBuilder("./assets/images/amnaStaff1.png"),
  amnaStop1: new AttachmentBuilder("./assets/images/amnaStop1.png"),
  amnaSubInlineText1: new AttachmentBuilder(
    "./assets/images/amnaSubInlineText1.png",
  ),
  amnaSubInlineText2: new AttachmentBuilder(
    "./assets/images/amnaSubInlineText2.png",
  ),
  amnaSuccess1: new AttachmentBuilder("./assets/images/amnaSuccess1.png"),
  amnaVolumeDown1: new AttachmentBuilder("./assets/images/amnaVolumeDown1.png"),
  amnaVolumeUp1: new AttachmentBuilder("./assets/images/amnaVolumeUp1.png"),
  ban1: new AttachmentBuilder("./assets/images/ban1.png"),
  Mypfp1: new AttachmentBuilder("./assets/images/Mypfp1.png"),
  NesCioFooter1: new AttachmentBuilder("./assets/images/NesCio-footer1.png"),
  other1: new AttachmentBuilder("./assets/images/other1.png"),
  supportTicket: new AttachmentBuilder("./assets/images/Support Ticket.png"),
};

module.exports = Image;
